version: '3.9'

services:
  
  db:
    image: mysql:8
    ports:
      - "3310:3310"
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #  - dbdata:/var/lib/mysql
    restart: always
    command: --lower_case_table_names=1
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: staff_scheduler
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpassword

  api:
     depends_on:
       - db
     image: staffscheduler:runtime
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     build:
       context: .
     ports:
       - "5501:80"
#volumes:
#  dbdata:
