version: '3.9'

services:
  
  db:
    image: mysql:8
    ports:
      - "3310:3310"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: staff_scheduler
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpassword

  api:
     depends_on:
       - db
     image: staffscheduler:runtime
     build:
       context: .
     ports:
       - "5501:80"
